### PR TITLE
feat: reuse host

### LINKED ISSUE #53: Reuse long running libp2p host for checks
## What's the problem

Running the `ipfs-check` backend on a machine behind NAT will fail running checks against other peers behind NAT, because we create a short-lived test host for the check, which doesn't connect to any peers, so it can't find any observed addrs, preventing NAT hole punching from happening.

### Reuse the long running libp2p peer for checks that don't involve an explicit multiaddr

Since the DHT traversal which happens as part of the check will likely open a connection (and hole punch) to a peer, we could reuse the long running libp2p host and pass it into Vole for the bitswap check.This would simplify the code and speed up the response. 

Moreover, this would ensure higher success rates for users running this backend behind NAT.

### Reduce activation threshold

Unfortunately, this configuration is global, so may not work for us, but this solved a similar problem in Vole https://github.com/ipfs-shipyard/vole/pull/39/files

### PR DESCRIPTION
**Pull request by 2color**
Fixes #53

### CODE REVIEW

**Review by SgtPooki — COMMENTED** [review]
i'm not sure I understand enough of this one to give a quality review even after reading https://github.com/ipfs/ipfs-check/issues/53

things I see changing in this PR:
* It seems like we're no longer using the testHost to make the initial connection, instead using the libp2p daemon host.
* It looks like the code used to only use the result of `createTestHost` to try connections, and we're no longer doing that. Makes sense when considering #53 

Questions:

* whats the difference between the result of `createTestHost` and `d.h` ? I'm guessing the `d.h` is the libp2p daemon host, but what exactly is the testHost?

**Comment by 2color** [comment]
> whats the difference between the result of createTestHost and d.h ? I'm guessing the d.h is the libp2p daemon host, but what exactly is the testHost?

They're both libp2p hosts/peers.

They are configured slightly differently. For example, `d.h` is a DHT Client, so it connects to other peers (which helps with things like discovering your own public IPs etc.) 

The test host we create is a "fresh clean" peer that is used just for the purpose of the test.

**Review by lidel — COMMENTED** [review]
Triage question: is this still blocked @2color ? (if so, on what?)

**Comment by 2color** [comment]
Closing this for now. Need to rethink this (ideally in #53)

**Pull request closed without merging**
